name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug environment information
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "System information:"
          uname -a
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Verify Node.js setup
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          
      - name: Install dependencies
        run: npm ci
        
      - name: List installed packages
        run: npm list --depth=0
        
      - name: Build
        run: npm run build
        
      - name: Verify build output
        run: |
          echo "Build directory contents:"
          ls -la dist || echo "dist directory not found!"
        
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BIRTHDAY_PROJECT_A72F9 }}
          channelId: live
          projectId: birthday-project-a72f9